### PR TITLE
Add checks decoupling ADR

### PR DESCRIPTION
**Pull request by dottorblaster**
Adding an ADR to sum up the state of the discussion about the checks' decoupling

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
Thank you @dottorblaster 
My doubt now is how we are going to ship the currently existing checks.
Are we going to have some of them in the wanda project, or are we going to move all checks to a separated project?
And specially how we deliver the checks in a k3s setup. Is the user required to install the checks using the RPM and mount the folder in k3s?
I'm talking more about the delivery and installation than the decoupling itself.

PD: specially in cloud based k3s deployments, where the user cannot go and install RPM packages and mount volumes as they wish

**Comment by dottorblaster** [comment]
@arbulu89 you're right, I was assuming too much :smile: 

The plan there is having a separate repo for all the checks, build the volume through our infrastructure and then publish the volume to our registry, so we can put that into our own Helm chart and users can download the artifact automatically.

I'll write that into the ADR, thanks for the feedback!

**Comment by dottorblaster** [comment]
Also on a second thought I have to play a bit with OBS in order to get an image of our checks :grimacing: thanks for pointing that out!

**Comment by dottorblaster** [comment]
@arbulu89 in the end we will have to mount a shared volume between Wanda and a sidecar container that will have to copy the checks on startup. Thanks for pointing that out, I completely missed that one.

**Pull request merged**
