### PR TITLE
Update RPM and Docker Installation Instructions for trento-checks

### PR DESCRIPTION
**Pull request by janvhs**
This PR updates the installation instructions to include the new `trento-checks` package.

For RPM based installations it is quite easy, since the user can just install `trento-checks`. For the Docker method there is however an open question.

How does the user manage the checks in a manual Docker install?

1. The user downloads the checks to their local file system and mounts them as a volume to the container's `/usr/trento/checks` mount point,
2. We ship an OCI artifact, if that's possible for this setup
3. The user derives from the wanda image with their own OCI image and installs the checks there.
4. Wanda preinstalls trento-checks and we instruct the user how to do 1. or 3.

What do you think @dottorblaster ?

### CODE REVIEW

**Review by dottorblaster — APPROVED** [review]
To me this looks good, maybe let's wait merging this until we have also the containers/kubernetes part so we can update all at once?

**Comment by EMaksy** [comment]
Hey great job @janvhs!
As a comment:
+1 to what @dottorblaster  said, let's wait until we have everything together!
Why?  Well the manual installation guide must be migrated to the [official documentation](https://documentation.suse.com/sles-sap/trento/html/SLES-SAP-trento/index.html#sec-trento-installing-trentoserver), which has a different structure and it is easier to do it once then multiple times :)

**Review by EMaksy — COMMENTED** [review]
Just saw a small thing, have a look  :+1:

**Review by dottorblaster — APPROVED** [review]
@janvhs just rebase this and merge :+1:

**Pull request merged**
